-- 코드를 입력하세요
# SELECT a.USER_ID, a.PRODUCT_ID FROM ONLINE_SALE a JOIN ONLINE_SALE b WHERE a.USER_ID = b.USER_ID AND a.PRODUCT_ID = b.PRODUCT_ID and a.ONLINE_SALE_ID != b.ONLINE_SALE_ID
# SELECT * FROm ONLINE_SALE;
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE 
GROUP BY USER_ID , PRODUCT_ID
HAVING COUNT(USER_ID) >1
ORDER BY USER_ID, PRODUCT_ID desc