# -- 코드를 입력하세요
# SELECT DATE_FORMAT(c.SALES_DATE,'%Y-%m-%d') as SALES_DATE, c.PRODUCT_ID, IFNULL(c.USER_ID,'NULL') as USER_ID, c.SALES_AMOUNT
# FROM (
    SELECT DATE_FORMAT(a.SALES_DATE,'%Y-%m-%d') as SALES_DATE, a.PRODUCT_ID, a.USER_ID, a.SALES_AMOUNT
    FROM ONLINE_SALE a
    WHERE YEAR(SALES_DATE) = '2022' and MONTH(SALES_DATE) = '03'
    UNION
    SELECT DATE_FORMAT(b.SALES_DATE,'%Y-%m-%d') as SALES_DATE, b.PRODUCT_ID, NULL, b.SALES_AMOUNT
    FROM OFFLINE_SALE b
    WHERE YEAR(SALES_DATE) = '2022' and MONTH(SALES_DATE) = '03'
    ORDER BY SALES_DATE asc, PRODUCT_ID asc, USER_ID asc;
# ) c
# WHERE YEAR(c.SALES_DATE) = '2022' and MONTH(c.SALES_DATE) = '03'
# # GROUP BY c.SALES_DATE, c.PRODUCT_ID
# ORDER BY c.SALES_DATE asc, c.PRODUCT_ID asc, c.USER_ID asc;