# -- 코드를 입력하세요
# SELECT *
# FROM (
    
# )
WITH TEMP AS(
SELECT CAR_ID, '대여중' as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
UNION
SELECT CAR_ID, '대여 가능' as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE '2022-10-16' NOT BETWEEN START_DATE AND END_DATE
ORDER BY CAR_ID, AVAILABILITY desc
)
SELECT * 
FROM TEMP
GROUP BY CAR_ID
ORDER BY CAR_ID desc
