-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, p.PRICE * SUM(AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT p
left join FOOD_ORDER o
on p.PRODUCT_ID = o.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = 2022 AND MONTH(o.PRODUCE_DATE) = 05
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES desc, p.PRODUCT_ID