-- 코드를 입력하세요 FIRST_HALF, JULY - SHIPMENT_ID
SELECT c.FLAVOR
FROM (
    SELECT *
    FROM FIRST_HALF

    UNION

    SELECT *
    FROM JULY
     )c
GROUP BY c.FLAVOR
ORDER BY SUM(c.TOTAL_ORDER) desc
LIMIT 3;