# -- 코드를 입력하세요
WITH temp as (
    SELECT c.MEMBER_ID, COUNT(c.MEMBER_ID) as r
    FROM REST_REVIEW c
    GROUP BY c.MEMBER_ID
    ORDER BY r desc
    LIMIT 1
)
# SELECT * FROM temp;
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE m
JOIN REST_REVIEW r on m.MEMBER_ID = r.MEMBER_ID
RIGHT JOIN temp t on m.MEMBER_ID = t.MEMBER_ID
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT;